# Generated by Django 4.1.7 on 2024-04-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('target_corpus_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadedCorpus',
            fields=[
                ('corpus_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('corpuses_history', models.JSONField(null=True)),
                ('current_task', models.BigIntegerField(null=True)),
            ],
        ),
    ]
