# Generated by Django 4.1.7 on 2024-07-16 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusHeaderV4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DjCorpusV4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_text', models.TextField()),
                ('p_div_locs', models.TextField()),
                ('index', models.IntegerField()),
                ('corpus_header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.corpusheaderv4')),
            ],
            options={
                'unique_together': {('corpus_header_id', 'index')},
            },
        ),
        migrations.CreateModel(
            name='DjParagraphDelimiterV4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('char', models.TextField(unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='CorpusHeader',
            new_name='CorpusHeaderV3',
        ),
        migrations.RenameModel(
            old_name='DjCorpus',
            new_name='DjCorpusV3',
        ),
        migrations.RenameModel(
            old_name='DjParagraphDelimitersInCorpus',
            new_name='DjParagraphDelimitersInCorpusV3',
        ),
        migrations.RenameModel(
            old_name='DjParagraphDelimiter',
            new_name='DjParagraphDelimiterV3',
        ),
        migrations.RenameModel(
            old_name='DjParagraph',
            new_name='DjParagraphV3',
        ),
        migrations.RenameModel(
            old_name='DjToken',
            new_name='DjTokenV3',
        ),
        migrations.RenameModel(
            old_name='TaskInfo',
            new_name='TaskInfoV3',
        ),
        migrations.CreateModel(
            name='TaskInfoV4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('RUNNING', 'Running'), ('FINISHED', 'Finished'), ('ERROR', 'Error'), ('ABORTED', 'Aborted')], default='READY', max_length=16)),
                ('target_corpus_header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.corpusheaderv4')),
            ],
        ),
        migrations.CreateModel(
            name='DjParagraphV4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tokens_json', models.JSONField(null=True)),
                ('pstate', models.CharField(choices=[('PLAIN', 'PLAIN'), ('DIVIDED', 'DIVIDED'), ('PARSED', 'PARSED'), ('ANNOTATED', 'ANNOTATED')], max_length=16)),
                ('is_delimiter', models.BooleanField()),
                ('token_delimiters', models.TextField()),
                ('annotator_info', models.TextField()),
                ('original_text', models.TextField()),
                ('index', models.IntegerField()),
                ('corpus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.djcorpusv4')),
            ],
            options={
                'unique_together': {('corpus_id', 'index')},
            },
        ),
        migrations.CreateModel(
            name='DjParagraphDelimitersInCorpusV4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.djcorpusv4')),
                ('paragraph_delimiter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.djparagraphdelimiterv4')),
            ],
            options={
                'unique_together': {('corpus_id', 'paragraph_delimiter_id')},
            },
        ),
    ]
