@startuml

class Token <<serializable>> {
	string txt
	string gloss

	bool is_delimiter
}

class Paragraph <<serializable>> {
	Token[] tokens
}
Paragraph o-left- Token

class Corpus <<serializable>> {
	int version = 5
	Object metadata

	Paragraph[] paragraphs
}
Corpus o-left- Paragraph

@enduml