@startuml

class DivideOptions <<serializable>> {
	string[] p_delims
}

class ParseOptions <<serializable>> {
	char[] t_delims
}
note left of ParseOptions::t_delims
	can be null
end note

class AnnotateOptions <<serializable>> {
	string lang_from
	string lang_to

	string annotator_name

	int[] target_paragraphs
}
note left of AnnotateOptions::annotator_name
	can be:
	  - null
	  - "chatgpt_ft0"
	  - "user_chatgpt_0"
	  - "user_chatgpt_1"
	  - ...
end note
note left of AnnotateOptions::target_paragraphs
	can be null
		(= all)
end note


class ReannotateOptions <<serializable>> {
	int[] target_tokens
}
@enduml