@startuml

entity DjToken {
	* id
	--
	txt
	gloss
	is_delimiter
	--
}

entity DjParagraph {
	* id
	--
	pstate
	is_delimiter
	token_delimiters
	annotator_info
	original_text
}

interface DjTokensInParagraph {
	* //DjParagraph.id//
	* index
	* //DjToken.id//
	--
}
DjToken ||-right-|| DjTokensInParagraph
DjTokensInParagraph }o-right-|| DjParagraph

entity DjCorpus {
	* id
	--
	orignal_text
	p_div_locs
}

interface DjParagraphsInCorpus {
	* //DjCorpus.id//
	* index
	* //DjParagraph.id//
	--
}
DjParagraph ||-right-|| DjParagraphsInCorpus
DjParagraphsInCorpus }o-right-|| DjCorpus

entity DjParagraphDelimiter {
	* id
	str //unique//
}

interface DjParagraphDelimitersInCorpus {
	* //DjCorpus.id//
	* //DjParagraphDelimiter.id//
}
DjCorpus ||-up-o{ DjParagraphDelimitersInCorpus
DjParagraphDelimitersInCorpus }o-up-|| DjParagraphDelimiter

entity CorpusHeader {
	* id
	---
	current_task
}

interface DjCorpusInCorpusInfo {
	* //DjCorpus.id//
	* index
	* //CorpusHeader.id//
}
DjCorpus ||-down-|| DjCorpusInCorpusInfo
DjCorpusInCorpusInfo }|-down-|| CorpusHeader

entity TaskInfo {
	* id
	--
	timestamp
	status
}

interface TaskTargetCorpus {
	* //TaskInfo.id//
	* //CorpusHeader.id//
}
CorpusHeader ||-left-o| TaskTargetCorpus
TaskTargetCorpus ||-left-|| TaskInfo

@enduml