@startuml

entity DjParagraph {
	* id
	--
	tokens

	pstate
	is_delimiter
	token_delimiters
	<strike>annotator_info</strike>
	original_text
}

interface DjAnnotatorInfo {
	*DjParagraph.id
	--
	lang_from
	lang_to
	annotator_name
}
DjParagraph ||-up-|| DjAnnotatorInfo

entity DjCorpus {
	* id
	--
	orignal_text
	p_div_locs
}

interface DjParagraphsInCorpus {
	* //DjCorpus.id//
	* index
	* //DjParagraph.id//
	--
}
DjParagraph ||-right-|| DjParagraphsInCorpus
DjParagraphsInCorpus }o-right-|| DjCorpus

entity DjParagraphDelimiter {
	* id
	str //unique//
}

interface DjParagraphDelimitersInCorpus {
	* //DjCorpus.id//
	* //DjParagraphDelimiter.id//
}
DjCorpus ||-up-o{ DjParagraphDelimitersInCorpus
DjParagraphDelimitersInCorpus }o-up-|| DjParagraphDelimiter

entity CorpusHeader {
	* id
	---
	user
}

interface DjCorpusInCorpusInfo {
	* //DjCorpus.id//
	* index
	* //CorpusHeader.id//
}
DjCorpus ||-down-|| DjCorpusInCorpusInfo
DjCorpusInCorpusInfo }|-down-|| CorpusHeader

entity TaskInfo {
	* id
	--
	timestamp
	status
}

interface TaskTargetCorpus {
	* //TaskInfo.id//
	* //CorpusHeader.id//
}
CorpusHeader ||-left-o| TaskTargetCorpus
TaskTargetCorpus ||-left-|| TaskInfo

@enduml