@startuml

class UploadedCorpus {
	string corpus_id

	Corpus[] corpuses_history

	string current_task
	
	void add_corpus(Corpus c)
}

class Task {
	string task_id
	Datetime timestamp

	string target_corpus_id
	string status
	string[] logs

	void run(function func, dict data)
	void abort()
}

enum TaskState {
	READY
	RUNNING
	FINISHED

	ERROR
	ABORTED
}
Task *-- TaskState

@enduml